spring:
  application:
    name: st-microservice-administration
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7986
  
logging:
  level:
    org:
      hibernate:
        SQL: debug